clear_variables();

maxFreq = 10;
switches = 1;//number of switches to be made
pausems = 150;//pause between each switch inside once cycle
pauseCyclems = 2000;//pause between cycles


W=WINDOW(ch1);
N=count(ch1);
measuredSignals = matrix(4*switches,N);
baseSignals = matrix(4,N);

set_trans_mask(15);
set_trans_mask(14);
sleep(pausems);

acquire(1, back1, 2, back2, 3, back3, 4, back4);

set_matrix_row(baseSignals,0,back1);
set_matrix_row(baseSignals,1,back2);
set_matrix_row(baseSignals,2,back3);
set_matrix_row(baseSignals,3,back4);
	
set_trans_mask(15);
set_trans_mask(13);
sleep(pausems);

acquire(1,back1, 2, back2, 3, back3, 4, back4);

	set_matrix_row(mt,16,back1);
	set_matrix_row(mt,17,push(back1,-shift));
	set_matrix_row(mt,18,back2);
	set_matrix_row(mt,19,push(back2,-shift));
	set_matrix_row(mt,20,back3);
	set_matrix_row(mt,21,push(back3,-shift));
	set_matrix_row(mt,22,back4);
	set_matrix_row(mt,23,push(back4,-shift));
	set_matrix_row(mt,24,back5);
	set_matrix_row(mt,25,push(back5,-shift));
	set_matrix_row(mt,26,back6);
	set_matrix_row(mt,27,push(back6,-shift));
	set_matrix_row(mt,28,back7);
	set_matrix_row(mt,29,push(back7,-shift));
	set_matrix_row(mt,30,back8);
	set_matrix_row(mt,31,push(back8,-shift));

	set_trans_mask(15);
	set_trans_mask(11);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	set_matrix_row(mt,32,back1);
	set_matrix_row(mt,33,push(back1,-shift));
	set_matrix_row(mt,34,back2);
	set_matrix_row(mt,35,push(back2,-shift));
	set_matrix_row(mt,36,back3);
	set_matrix_row(mt,37,push(back3,-shift));
	set_matrix_row(mt,38,back4);
	set_matrix_row(mt,39,push(back4,-shift));
	set_matrix_row(mt,40,back5);
	set_matrix_row(mt,41,push(back5,-shift));
	set_matrix_row(mt,42,back6);
	set_matrix_row(mt,43,push(back6,-shift));
	set_matrix_row(mt,44,back7);
	set_matrix_row(mt,45,push(back7,-shift));
	set_matrix_row(mt,46,back8);
	set_matrix_row(mt,47,push(back8,-shift));

	set_trans_mask(15);
	set_trans_mask(7);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);


	set_matrix_row(mt,48,back1);
	set_matrix_row(mt,49,push(back1,-shift));
	set_matrix_row(mt,50,back2);
	set_matrix_row(mt,51,push(back2,-shift));
	set_matrix_row(mt,52,back3);
	set_matrix_row(mt,53,push(back3,-shift));
	set_matrix_row(mt,54,back4);
	set_matrix_row(mt,55,push(back4,-shift));
	set_matrix_row(mt,56,back5);
	set_matrix_row(mt,57,push(back5,-shift));
	set_matrix_row(mt,58,back6);
	set_matrix_row(mt,59,push(back6,-shift));
	set_matrix_row(mt,60,back7);
	set_matrix_row(mt,61,push(back7,-shift));
	set_matrix_row(mt,62,back8);
	set_matrix_row(mt,63,push(back8,-shift));

	set_trans_mask(15);
	set_trans_mask(14);

	sleep(pauseCyclems);

for (ia = 0; ia < switches; ia = ia +1)
{
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	set_matrix_row(mt,0, back1 - get_matrix_row(mt, 0));
	set_matrix_row(mt,1, push(back1,-shift) - get_matrix_row(mt, 1));
	set_matrix_row(mt,2, back2 - get_matrix_row(mt, 2));
	set_matrix_row(mt,3, push(back2,-shift) - get_matrix_row(mt, 3));
	set_matrix_row(mt,4, back3 - get_matrix_row(mt, 4));
	set_matrix_row(mt,5, push(back3,-shift) - get_matrix_row(mt, 5));
	set_matrix_row(mt,6, back4 - get_matrix_row(mt, 6));
	set_matrix_row(mt,7, push(back4,-shift) - get_matrix_row(mt, 7));
	set_matrix_row(mt,8, back5 - get_matrix_row(mt, 8));
	set_matrix_row(mt,9, push(back5,-shift) - get_matrix_row(mt, 9));
	set_matrix_row(mt,10, back6 - get_matrix_row(mt, 10));
	set_matrix_row(mt,11, push(back6,-shift) - get_matrix_row(mt, 11));
	set_matrix_row(mt,12, back7 - get_matrix_row(mt, 12));
	set_matrix_row(mt,13, push(back7,-shift) - get_matrix_row(mt, 13));
	set_matrix_row(mt,14, back8 - get_matrix_row(mt, 14));
	set_matrix_row(mt,15, push(back8,-shift) - get_matrix_row(mt, 15));

	set_trans_mask(15);
	set_trans_mask(13);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	set_matrix_row(mt,16, back1 - get_matrix_row(mt, 16));
	set_matrix_row(mt,17, push(back1,-shift) - get_matrix_row(mt, 17));
	set_matrix_row(mt,18, back2 - get_matrix_row(mt, 18));
	set_matrix_row(mt,19, push(back2,-shift) - get_matrix_row(mt, 19));
	set_matrix_row(mt,20, back3 - get_matrix_row(mt, 20));
	set_matrix_row(mt,21, push(back3,-shift) - get_matrix_row(mt, 21));
	set_matrix_row(mt,22, back4 - get_matrix_row(mt, 22));
	set_matrix_row(mt,23, push(back4,-shift) - get_matrix_row(mt, 23));
	set_matrix_row(mt,24, back5 - get_matrix_row(mt, 24));
	set_matrix_row(mt,25, push(back5,-shift) - get_matrix_row(mt, 25));
	set_matrix_row(mt,26, back6 - get_matrix_row(mt, 26));
	set_matrix_row(mt,27, push(back6,-shift) - get_matrix_row(mt, 27));
	set_matrix_row(mt,28, back7 - get_matrix_row(mt, 28));
	set_matrix_row(mt,29, push(back7,-shift) - get_matrix_row(mt, 29));
	set_matrix_row(mt,30, back8 - get_matrix_row(mt, 30));
	set_matrix_row(mt,31, push(back8,-shift) - get_matrix_row(mt, 31));


	set_trans_mask(15);
	set_trans_mask(11);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	r13 = back1;
	r14 = get_matrix_row(mt, 32);
	set_matrix_row(mt,32, back1 - get_matrix_row(mt, 32));
	set_matrix_row(mt,33, push(back1,-shift) - get_matrix_row(mt, 33));
	set_matrix_row(mt,34, back2 - get_matrix_row(mt, 34));
	set_matrix_row(mt,35, push(back2,-shift) - get_matrix_row(mt, 35));
	set_matrix_row(mt,36, back3 - get_matrix_row(mt, 36));
	set_matrix_row(mt,37, push(back3,-shift) - get_matrix_row(mt, 37));
	set_matrix_row(mt,38, back4 - get_matrix_row(mt, 38));
	set_matrix_row(mt,39, push(back4,-shift) - get_matrix_row(mt, 39));
	set_matrix_row(mt,40, back5 - get_matrix_row(mt, 40));
	set_matrix_row(mt,41, push(back5,-shift) - get_matrix_row(mt, 41));
	set_matrix_row(mt,42, back6 - get_matrix_row(mt, 42));
	set_matrix_row(mt,43, push(back6,-shift) - get_matrix_row(mt, 43));
	set_matrix_row(mt,44, back7 - get_matrix_row(mt, 44));
	set_matrix_row(mt,45, push(back7,-shift) - get_matrix_row(mt, 45));
	set_matrix_row(mt,46, back8 - get_matrix_row(mt, 46));
	set_matrix_row(mt,47, push(back8,-shift) - get_matrix_row(mt, 47));

	set_trans_mask(15);
	set_trans_mask(7);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	r11 = back1;
	r12 = get_matrix_row(mt, 48);
	set_matrix_row(mt,48, back1 - get_matrix_row(mt, 48));
	
	set_matrix_row(mt,49, push(back1,-shift) - get_matrix_row(mt, 49));
	set_matrix_row(mt,50, back2 - get_matrix_row(mt, 50));
	set_matrix_row(mt,51, push(back2,-shift) - get_matrix_row(mt, 51));
	set_matrix_row(mt,52, back3 - get_matrix_row(mt, 52));
	set_matrix_row(mt,53, push(back3,-shift) - get_matrix_row(mt, 53));
	set_matrix_row(mt,54, back4 - get_matrix_row(mt, 54));
	set_matrix_row(mt,55, push(back4,-shift) - get_matrix_row(mt, 55));
	set_matrix_row(mt,56, back5 - get_matrix_row(mt, 56));
	set_matrix_row(mt,57, push(back5,-shift) - get_matrix_row(mt, 57));
	set_matrix_row(mt,58, back6 - get_matrix_row(mt, 58));
	set_matrix_row(mt,59, push(back6,-shift) - get_matrix_row(mt, 59));
	set_matrix_row(mt,60, back7 - get_matrix_row(mt, 60));
	set_matrix_row(mt,61, push(back7,-shift) - get_matrix_row(mt, 61));
	set_matrix_row(mt,62, back8 - get_matrix_row(mt, 62));
	set_matrix_row(mt,63, push(back8,-shift) - get_matrix_row(mt, 63));
	
	
	
	
	set_trans_mask(15);
	set_trans_mask(14);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);


	set_matrix_row(mt,0,back1);
	set_matrix_row(mt,1,push(back1,-shift));
	set_matrix_row(mt,2,back2);
	set_matrix_row(mt,3,push(back2,-shift));
	set_matrix_row(mt,4,back3);
	set_matrix_row(mt,5,push(back3,-shift));
	set_matrix_row(mt,6,back4);
	set_matrix_row(mt,7,push(back4,-shift));
	set_matrix_row(mt,8,back5);
	set_matrix_row(mt,9,push(back5,-shift));
	set_matrix_row(mt,10,back6);
	set_matrix_row(mt,11,push(back6,-shift));
	set_matrix_row(mt,12,back7);
	set_matrix_row(mt,13,push(back7,-shift));
	set_matrix_row(mt,14,back8);
	set_matrix_row(mt,15,push(back8,-shift));
	
	set_trans_mask(15);
	set_trans_mask(13);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	set_matrix_row(mt,16,back1);
	set_matrix_row(mt,17,push(back1,-shift));
	set_matrix_row(mt,18,back2);
	set_matrix_row(mt,19,push(back2,-shift));
	set_matrix_row(mt,20,back3);
	set_matrix_row(mt,21,push(back3,-shift));
	set_matrix_row(mt,22,back4);
	set_matrix_row(mt,23,push(back4,-shift));
	set_matrix_row(mt,24,back5);
	set_matrix_row(mt,25,push(back5,-shift));
	set_matrix_row(mt,26,back6);
	set_matrix_row(mt,27,push(back6,-shift));
	set_matrix_row(mt,28,back7);
	set_matrix_row(mt,29,push(back7,-shift));
	set_matrix_row(mt,30,back8);
	set_matrix_row(mt,31,push(back8,-shift));

	set_trans_mask(15);
	set_trans_mask(11);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	set_matrix_row(mt,32,back1);
	set_matrix_row(mt,33,push(back1,-shift));
	set_matrix_row(mt,34,back2);
	set_matrix_row(mt,35,push(back2,-shift));
	set_matrix_row(mt,36,back3);
	set_matrix_row(mt,37,push(back3,-shift));
	set_matrix_row(mt,38,back4);
	set_matrix_row(mt,39,push(back4,-shift));
	set_matrix_row(mt,40,back5);
	set_matrix_row(mt,41,push(back5,-shift));
	set_matrix_row(mt,42,back6);
	set_matrix_row(mt,43,push(back6,-shift));
	set_matrix_row(mt,44,back7);
	set_matrix_row(mt,45,push(back7,-shift));
	set_matrix_row(mt,46,back8);
	set_matrix_row(mt,47,push(back8,-shift));

	set_trans_mask(15);
	set_trans_mask(7);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);


	set_matrix_row(mt,48,back1);
	set_matrix_row(mt,49,push(back1,-shift));
	set_matrix_row(mt,50,back2);
	set_matrix_row(mt,51,push(back2,-shift));
	set_matrix_row(mt,52,back3);
	set_matrix_row(mt,53,push(back3,-shift));
	set_matrix_row(mt,54,back4);
	set_matrix_row(mt,55,push(back4,-shift));
	set_matrix_row(mt,56,back5);
	set_matrix_row(mt,57,push(back5,-shift));
	set_matrix_row(mt,58,back6);
	set_matrix_row(mt,59,push(back6,-shift));
	set_matrix_row(mt,60,back7);
	set_matrix_row(mt,61,push(back7,-shift));
	set_matrix_row(mt,62,back8);
	set_matrix_row(mt,63,push(back8,-shift));

	set_trans_mask(15);
	set_trans_mask(14);

	sleep(3000);

	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	set_matrix_row(mt,0, back1 - get_matrix_row(mt, 0));
	set_matrix_row(mt,1, push(back1,-shift) - get_matrix_row(mt, 1));
	set_matrix_row(mt,2, back2 - get_matrix_row(mt, 2));
	set_matrix_row(mt,3, push(back2,-shift) - get_matrix_row(mt, 3));
	set_matrix_row(mt,4, back3 - get_matrix_row(mt, 4));
	set_matrix_row(mt,5, push(back3,-shift) - get_matrix_row(mt, 5));
	set_matrix_row(mt,6, back4 - get_matrix_row(mt, 6));
	set_matrix_row(mt,7, push(back4,-shift) - get_matrix_row(mt, 7));
	set_matrix_row(mt,8, back5 - get_matrix_row(mt, 8));
	set_matrix_row(mt,9, push(back5,-shift) - get_matrix_row(mt, 9));
	set_matrix_row(mt,10, back6 - get_matrix_row(mt, 10));
	set_matrix_row(mt,11, push(back6,-shift) - get_matrix_row(mt, 11));
	set_matrix_row(mt,12, back7 - get_matrix_row(mt, 12));
	set_matrix_row(mt,13, push(back7,-shift) - get_matrix_row(mt, 13));
	set_matrix_row(mt,14, back8 - get_matrix_row(mt, 14));
	set_matrix_row(mt,15, push(back8,-shift) - get_matrix_row(mt, 15));

	set_trans_mask(15);
	set_trans_mask(13);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	set_matrix_row(mt,16, back1 - get_matrix_row(mt, 16));
	set_matrix_row(mt,17, push(back1,-shift) - get_matrix_row(mt, 17));
	set_matrix_row(mt,18, back2 - get_matrix_row(mt, 18));
	set_matrix_row(mt,19, push(back2,-shift) - get_matrix_row(mt, 19));
	set_matrix_row(mt,20, back3 - get_matrix_row(mt, 20));
	set_matrix_row(mt,21, push(back3,-shift) - get_matrix_row(mt, 21));
	set_matrix_row(mt,22, back4 - get_matrix_row(mt, 22));
	set_matrix_row(mt,23, push(back4,-shift) - get_matrix_row(mt, 23));
	set_matrix_row(mt,24, back5 - get_matrix_row(mt, 24));
	set_matrix_row(mt,25, push(back5,-shift) - get_matrix_row(mt, 25));
	set_matrix_row(mt,26, back6 - get_matrix_row(mt, 26));
	set_matrix_row(mt,27, push(back6,-shift) - get_matrix_row(mt, 27));
	set_matrix_row(mt,28, back7 - get_matrix_row(mt, 28));
	set_matrix_row(mt,29, push(back7,-shift) - get_matrix_row(mt, 29));
	set_matrix_row(mt,30, back8 - get_matrix_row(mt, 30));
	set_matrix_row(mt,31, push(back8,-shift) - get_matrix_row(mt, 31));


	set_trans_mask(15);
	set_trans_mask(11);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	r13 = back1;
	r14 = get_matrix_row(mt, 32);
	set_matrix_row(mt,32, back1 - get_matrix_row(mt, 32));
	set_matrix_row(mt,33, push(back1,-shift) - get_matrix_row(mt, 33));
	set_matrix_row(mt,34, back2 - get_matrix_row(mt, 34));
	set_matrix_row(mt,35, push(back2,-shift) - get_matrix_row(mt, 35));
	set_matrix_row(mt,36, back3 - get_matrix_row(mt, 36));
	set_matrix_row(mt,37, push(back3,-shift) - get_matrix_row(mt, 37));
	set_matrix_row(mt,38, back4 - get_matrix_row(mt, 38));
	set_matrix_row(mt,39, push(back4,-shift) - get_matrix_row(mt, 39));
	set_matrix_row(mt,40, back5 - get_matrix_row(mt, 40));
	set_matrix_row(mt,41, push(back5,-shift) - get_matrix_row(mt, 41));
	set_matrix_row(mt,42, back6 - get_matrix_row(mt, 42));
	set_matrix_row(mt,43, push(back6,-shift) - get_matrix_row(mt, 43));
	set_matrix_row(mt,44, back7 - get_matrix_row(mt, 44));
	set_matrix_row(mt,45, push(back7,-shift) - get_matrix_row(mt, 45));
	set_matrix_row(mt,46, back8 - get_matrix_row(mt, 46));
	set_matrix_row(mt,47, push(back8,-shift) - get_matrix_row(mt, 47));

	set_trans_mask(15);
	set_trans_mask(7);
	sleep(pausems);
	//acquire(255,255);
	acquire(1,back1, 2, back2, 3, back3,4,back4,5,back5, 6, back6, 7, back7,8,back8);

	r11 = back1;
	r12 = get_matrix_row(mt, 48);
	set_matrix_row(mt,48, back1 - get_matrix_row(mt, 48));
	
	set_matrix_row(mt,49, push(back1,-shift) - get_matrix_row(mt, 49));
	set_matrix_row(mt,50, back2 - get_matrix_row(mt, 50));
	set_matrix_row(mt,51, push(back2,-shift) - get_matrix_row(mt, 51));
	set_matrix_row(mt,52, back3 - get_matrix_row(mt, 52));
	set_matrix_row(mt,53, push(back3,-shift) - get_matrix_row(mt, 53));
	set_matrix_row(mt,54, back4 - get_matrix_row(mt, 54));
	set_matrix_row(mt,55, push(back4,-shift) - get_matrix_row(mt, 55));
	set_matrix_row(mt,56, back5 - get_matrix_row(mt, 56));
	set_matrix_row(mt,57, push(back5,-shift) - get_matrix_row(mt, 57));
	set_matrix_row(mt,58, back6 - get_matrix_row(mt, 58));
	set_matrix_row(mt,59, push(back6,-shift) - get_matrix_row(mt, 59));
	set_matrix_row(mt,60, back7 - get_matrix_row(mt, 60));
	set_matrix_row(mt,61, push(back7,-shift) - get_matrix_row(mt, 61));
	set_matrix_row(mt,62, back8 - get_matrix_row(mt, 62));
	set_matrix_row(mt,63, push(back8,-shift) - get_matrix_row(mt, 63));	
}
	
	
	
	




r1 = lf(get_matrix_row(signals,48),maxFreq,maxFreq*1.5,-6);
r2 = lf(get_matrix_row(signals,49),maxFreq,maxFreq*1.5,-6);
r3 = lf(get_matrix_row(signals,50),maxFreq,maxFreq*1.5,-6);
r4 = lf(get_matrix_row(signals,51),maxFreq,maxFreq*1.5,-6);
r5 = lf(get_matrix_row(signals,52),maxFreq,maxFreq*1.5,-6);
r6 = lf(get_matrix_row(signals,53),maxFreq,maxFreq*1.5,-6);
r7 = lf(get_matrix_row(signals,54),maxFreq,maxFreq*1.5,-6);
r8 = lf(get_matrix_row(signals,55),maxFreq,maxFreq*1.5,-6);
