test_signal = r2;
search_start = 0.05;
search_end = 0.4;
pos1 = 0;
pos2 = 0;
error = 0;
maximas = 5;
method = 2; // Search for equal number of maximas to the left and to the right

(error) = gate_maximas(test_signal, search_start, search_end, pos1, pos2, maximas, method);
//set_marker(1, 1, 10); // Not working
//set_marker(10, 1, 1); // Not working

if (error)
{
	  print_line("There was an error while finding the double maximums. Error code ", error);
}
else
{
	  print_line("Found maximums at: ", pos1, " and ", pos2);
}

low_threshold = 0.2;
high_threshold = 0.7;
(error) = gate_maximas_ex(test_signal, search_start, search_end, low_threshold, high_threshold, pos1, pos2, maximas, method);

if (error)
{
	  print_line("There was an error while finding the double maximums. Error code ", error);
}
else
{
	  print_line("Extended algorithm found maximums at: ", pos1, " and ", pos2);
}